name = "www"
type = "javascript"
account_id = "1741cdac872756d5703181c8cf7efbed"
workers_dev = true

[env.production]
workers_dev = false
route = "aidanblog.com/*"
zone_id = "b78798edbf0351f6ff74e67d71e5694d"

[site]
bucket = "./_site"
entry-point = "workers-site"
